plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.intellij.platform'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

group = providers.gradleProperty('pluginGroup').get()
version = providers.gradleProperty('pluginVersion').get()

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        androidStudio(
                providers.gradleProperty('platformVersion').get()
        )
        bundledPlugin('com.intellij.java')
    }

    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    testRuntimeOnly 'junit:junit:4.13.2'
}

intellijPlatform {
    pluginConfiguration {
        id = providers.gradleProperty('pluginId')
        name = providers.gradleProperty('pluginName')
        version = providers.gradleProperty('pluginVersion')
        description = providers.gradleProperty('pluginDescription')

        ideaVersion {
            sinceBuild = providers.gradleProperty('pluginSinceBuild')
            untilBuild = provider { null }
        }

        vendor {
            name = providers.gradleProperty('pluginVendor')
            email = providers.gradleProperty('pluginVendorEmail')
            url = providers.gradleProperty('pluginVendorUrl')
        }

        changeNotes = providers.gradleProperty('pluginChangeNotes')
    }

    publishing {
        token = providers.environmentVariable('PUBLISH_TOKEN')
    }

    signing {
        certificateChain = providers.environmentVariable('CERTIFICATE_CHAIN')
        privateKey = providers.environmentVariable('PRIVATE_KEY')
        password = providers.environmentVariable('PRIVATE_KEY_PASSWORD')
    }
}

tasks.withType(JavaCompile).configureEach {
    sourceCompatibility = JavaVersion.VERSION_17.toString()
    targetCompatibility = JavaVersion.VERSION_17.toString()
}

tasks {
    compileKotlin {
        compilerOptions {
            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
        }
    }

    compileTestKotlin {
        compilerOptions {
            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
        }
    }

    patchPluginXml {
        sinceBuild = providers.gradleProperty('pluginSinceBuild')
        untilBuild = provider { null }
    }

    test {
        useJUnitPlatform()
    }

    runIde {
        jvmArgs = ['-Xmx2g']
    }
}
