plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.intellij.platform'
}

group = providers.gradleProperty('pluginGroup').get()
version = providers.gradleProperty('pluginVersion').get()

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        androidStudio(
                providers.gradleProperty('platformVersion').get()
        )
        create(
                providers.gradleProperty('platformType').get(),
                providers.gradleProperty('platformVersion').get()
        )
        bundledPlugin('com.intellij.java')
        instrumentationTools()
        pluginVerifier()
        zipSigner()
        testFramework(org.jetbrains.intellij.platform.gradle.TestFrameworkType.Platform)
    }

    testImplementation "org.jetbrains.kotlin:kotlin-test"
}

kotlin {
    jvmToolchain(17)
}

intellijPlatform {
    pluginConfiguration {
        id = providers.gradleProperty('pluginId')
        name = providers.gradleProperty('pluginName')
        version = providers.gradleProperty('pluginVersion')
        description = providers.gradleProperty('pluginDescription')

        ideaVersion {
            sinceBuild = providers.gradleProperty('pluginSinceBuild')
            untilBuild = provider { null }
        }

        vendor {
            name = providers.gradleProperty('pluginVendor')
            email = providers.gradleProperty('pluginVendorEmail')
            url = providers.gradleProperty('pluginVendorUrl')
        }

        changeNotes = providers.gradleProperty('pluginChangeNotes')
    }

    publishing {
        token = providers.environmentVariable('PUBLISH_TOKEN')
    }

    signing {
        certificateChain = providers.environmentVariable('CERTIFICATE_CHAIN')
        privateKey = providers.environmentVariable('PRIVATE_KEY')
        password = providers.environmentVariable('PRIVATE_KEY_PASSWORD')
    }
}

tasks {
    patchPluginXml {
        sinceBuild = providers.gradleProperty('pluginSinceBuild')
        untilBuild = provider { null }
    }

    test {
        useJUnitPlatform()
    }

    runIde {
        jvmArgs = ['-Xmx2g']
    }
}
